"""Builds CML's Java <-> Bedrock texture path table.

Matches the vanilla textures of both editions by pixel content (exact RGBA hash first,
then a downscaled perceptual hash), then by name normalisation for the rest.

Usage: python tool/gen_texture_map.py <java client.jar> <bedrock resource_pack dir>
Writes lib/src/resourcepack/data/texture_map_data.dart
"""
import base64, gzip, hashlib, io, json, re, sys, zipfile
from collections import defaultdict
from pathlib import Path

from PIL import Image

jar, bed_root = sys.argv[1], Path(sys.argv[2])

def norm_img(im):
    im = im.convert('RGBA')
    return im

def exact(im):
    return hashlib.sha1(im.tobytes() + bytes(str(im.size), 'ascii')).hexdigest()

def phash(im):
    # 16x16 downscale of first square frame, alpha-premultiplied
    w, h = im.size
    if h > w and h % w == 0:
        im = im.crop((0, 0, w, w))
    sm = im.resize((16, 16), Image.NEAREST).convert('RGBA')
    px = list(sm.get_flattened_data()) if hasattr(sm, 'get_flattened_data') else list(sm.getdata())
    return tuple((r * a // 255 // 32, g * a // 255 // 32, b * a // 255 // 32, a // 64) for r, g, b, a in px)

# ---- java textures
java = {}
with zipfile.ZipFile(jar) as z:
    for n in z.namelist():
        if n.startswith('assets/minecraft/textures/') and n.endswith('.png'):
            rel = n[len('assets/minecraft/textures/'):-4]
            try:
                java[rel] = norm_img(Image.open(io.BytesIO(z.read(n))))
            except Exception:
                pass

# ---- bedrock textures (png + tga)
bed = {}
for p in (bed_root / 'textures').rglob('*'):
    if p.suffix.lower() not in ('.png', '.tga'):
        continue
    rel = p.relative_to(bed_root / 'textures').as_posix()[:-4]
    if rel in bed and p.suffix.lower() == '.tga':
        continue
    try:
        bed[rel] = norm_img(Image.open(p))
    except Exception:
        pass

print('java', len(java), 'bedrock', len(bed))

# ---- 1) exact pixel matches
by_exact = defaultdict(list)
for k, im in bed.items():
    by_exact[exact(im)].append(k)
by_phash = defaultdict(list)
for k, im in bed.items():
    by_phash[phash(im)].append(k)

TOP = {'block': 'blocks', 'item': 'items'}

def name_score(j, b):
    """prefer bedrock candidates in the analogous folder with similar names"""
    jt, bt = j.split('/')[0], b.split('/')[0]
    s = 0
    if TOP.get(jt, jt) == bt:
        s += 10
    jn = re.sub(r'[^a-z0-9]', '', j.split('/')[-1])
    bn = re.sub(r'[^a-z0-9]', '', b.split('/')[-1])
    s += len(set(jn) & set(bn)) / max(1, len(set(jn) | set(bn))) * 5
    if jn == bn:
        s += 20
    return s

mapping, how = {}, {}
used = defaultdict(int)
for j, im in java.items():
    cands = by_exact.get(exact(im))
    method = 'pixel'
    if not cands:
        cands = by_phash.get(phash(im))
        method = 'phash'
    if cands:
        best = max(cands, key=lambda b: name_score(j, b))
        mapping[j] = best
        how[j] = method

# ---- 2) name rules for unmatched textures
bed_keys = set(bed)
def name_candidates(j):
    top, _, rest = j.partition('/')
    btop = TOP.get(top, top)
    yield f'{btop}/{rest}'
    yield f'{btop}/{rest.replace("/", "_")}'
    flat = rest.split('/')[-1]
    yield f'{btop}/{flat}'
    for a, b in [('_planks', ''), ('_log', ''), ('_leaves', '')]:
        pass

for j in java:
    if j in mapping:
        continue
    for c in name_candidates(j):
        if c in bed_keys:
            mapping[j] = c
            how[j] = 'name'
            break

stats = defaultdict(int)
for v in how.values():
    stats[v] += 1
print('mapped', len(mapping), dict(stats), 'unmapped', len(java) - len(mapping))

# drop ambiguous many->one for non-pixel matches where a pixel match exists for the same target
target_pixel = {v for k, v in mapping.items() if how[k] == 'pixel'}
for k in list(mapping):
    if how[k] != 'pixel' and mapping[k] in target_pixel and Path(k).name != Path(mapping[k]).name:
        del mapping[k]

# terrain atlas keys (needed for Bedrock flipbook_textures.json)
atlas = {}
tt = bed_root / 'textures' / 'terrain_texture.json'
if tt.exists():
    raw = re.sub(r'(?m)^\s*//.*$', '', tt.read_text(encoding='utf-8'))
    for key, ent in json.loads(raw)['texture_data'].items():
        texs = ent.get('textures')
        for t in (texs if isinstance(texs, list) else [texs]):
            p = t.get('path') if isinstance(t, dict) else t
            if isinstance(p, str):
                atlas.setdefault(p[len('textures/'):] if p.startswith('textures/') else p, key)
lines = '\n'.join(f'{k}\t{v}\t{atlas.get(v, "")}' for k, v in sorted(mapping.items()))
blob = base64.b64encode(gzip.compress(lines.encode(), 9)).decode()
out = ['// GENERATED by tool/gen_texture_map.py — Java (assets/minecraft/textures) <-> Bedrock (textures) paths, without extension.',
       '// Built by matching vanilla texture pixels of both editions, then name rules. Format: gzip TSV "java\tbedrock\tterrainAtlasKey".',
       'const javaBedrockTexturesGz =']
out += ["    '%s'" % blob[i:i + 120] for i in range(0, len(blob), 120)]
out[-1] += ';'
Path('lib/src/resourcepack/data').mkdir(parents=True, exist_ok=True)
Path('lib/src/resourcepack/data/texture_map_data.dart').write_text('\n'.join(out) + '\n', encoding='utf-8')
print('final', len(mapping))
# show some unmapped samples per folder
un = defaultdict(list)
for j in java:
    if j not in mapping:
        un[j.split('/')[0]].append(j)
for k, v in un.items():
    print(' unmapped', k, len(v), v[:8])
