"""Regenerates lib/src/structure/data/block_map_data.dart.

Usage: python tool/gen_block_map.py path/to/GeyserMC-mappings/blocks.json
(blocks.json was replaced by blocks.nbt upstream after 2024-05; use commit cc3afdc9 or a mappings-generator run.)
"""
import base64, gzip, json, sys

d = json.load(open(sys.argv[1], encoding='utf-8'))
lines = []
for k, v in d.items():
    bid = v.get('bedrock_identifier')
    st = v.get('bedrock_states') or {}
    if bid == k.split('[')[0] and not st and '[' not in k:
        continue
    lines.append(k + '\t' + bid + '\t' + (json.dumps(st, separators=(',', ':'), sort_keys=True) if st else ''))
s = base64.b64encode(gzip.compress('\n'.join(lines).encode(), 9)).decode()
out = ['// GENERATED by tool/gen_block_map.py from GeyserMC/mappings blocks.json (MIT, Java 1.20.5 <-> Bedrock 1.20.80).',
       '// Format (gzip, TSV): javaState \t bedrockName \t bedrockStatesJson. Identity mappings without states are omitted.',
       '// ignore_for_file: lines_longer_than_80_chars',
       'const javaBedrockBlocksGz =']
out += ["    '%s'" % s[i:i + 120] for i in range(0, len(s), 120)]
out[-1] += ';'
open('lib/src/structure/data/block_map_data.dart', 'w').write('\n'.join(out) + '\n')
