// 函数说明（自动补全与参数提示）
export const FUNC_INFO = {
    SUM: ['SUM(数值1, [数值2], …)', '求和'],
    AVERAGE: ['AVERAGE(数值1, [数值2], …)', '平均值'],
    MIN: ['MIN(数值1, [数值2], …)', '最小值'],
    MAX: ['MAX(数值1, [数值2], …)', '最大值'],
    COUNT: ['COUNT(值1, [值2], …)', '统计数字个数'],
    COUNTA: ['COUNTA(值1, [值2], …)', '统计非空单元格个数'],
    COUNTBLANK: ['COUNTBLANK(区域)', '统计空单元格个数'],
    COUNTIF: ['COUNTIF(区域, 条件)', '统计满足条件的单元格个数'],
    COUNTIFS: ['COUNTIFS(区域1, 条件1, …)', '多条件计数'],
    SUMIF: ['SUMIF(区域, 条件, [求和区域])', '按条件求和'],
    SUMIFS: ['SUMIFS(求和区域, 区域1, 条件1, …)', '多条件求和'],
    AVERAGEIF: ['AVERAGEIF(区域, 条件, [平均区域])', '按条件求平均值'],
    AVERAGEIFS: ['AVERAGEIFS(平均区域, 区域1, 条件1, …)', '多条件平均值'],
    MAXIFS: ['MAXIFS(最大值区域, 区域1, 条件1, …)', '多条件最大值'],
    MINIFS: ['MINIFS(最小值区域, 区域1, 条件1, …)', '多条件最小值'],
    IF: ['IF(条件, 真值, [假值])', '条件判断'],
    IFS: ['IFS(条件1, 值1, [条件2, 值2], …)', '多条件判断'],
    IFERROR: ['IFERROR(值, 出错时的值)', '出错时返回指定值'],
    IFNA: ['IFNA(值, #N/A 时的值)', '#N/A 时返回指定值'],
    SWITCH: ['SWITCH(表达式, 值1, 结果1, …, [默认])', '按值选择结果'],
    AND: ['AND(逻辑1, [逻辑2], …)', '全部为真时返回 TRUE'],
    OR: ['OR(逻辑1, [逻辑2], …)', '任一为真时返回 TRUE'],
    NOT: ['NOT(逻辑值)', '取反'],
    XOR: ['XOR(逻辑1, [逻辑2], …)', '异或'],
    ROUND: ['ROUND(数值, 小数位数)', '四舍五入'],
    ROUNDUP: ['ROUNDUP(数值, 小数位数)', '向远离零方向舍入'],
    ROUNDDOWN: ['ROUNDDOWN(数值, 小数位数)', '向零方向舍入'],
    INT: ['INT(数值)', '向下取整'],
    TRUNC: ['TRUNC(数值, [小数位数])', '截断小数'],
    ABS: ['ABS(数值)', '绝对值'],
    SQRT: ['SQRT(数值)', '平方根'],
    POWER: ['POWER(底数, 指数)', '乘幂'],
    MOD: ['MOD(被除数, 除数)', '求余数'],
    PI: ['PI()', '圆周率 π'],
    RAND: ['RAND()', '0 到 1 之间的随机数'],
    RANDBETWEEN: ['RANDBETWEEN(下限, 上限)', '指定范围内的随机整数'],
    PRODUCT: ['PRODUCT(数值1, [数值2], …)', '乘积'],
    SUMPRODUCT: ['SUMPRODUCT(数组1, [数组2], …)', '对应元素乘积之和'],
    SUMSQ: ['SUMSQ(数值1, …)', '平方和'],
    CEILING: ['CEILING(数值, 基数)', '向上舍入到基数的倍数'],
    FLOOR: ['FLOOR(数值, 基数)', '向下舍入到基数的倍数'],
    EXP: ['EXP(数值)', 'e 的乘幂'], LN: ['LN(数值)', '自然对数'], LOG: ['LOG(数值, [底数])', '对数'], LOG10: ['LOG10(数值)', '常用对数'],
    SIGN: ['SIGN(数值)', '符号'], FACT: ['FACT(数值)', '阶乘'],
    SIN: ['SIN(弧度)', '正弦'], COS: ['COS(弧度)', '余弦'], TAN: ['TAN(弧度)', '正切'],
    RANK: ['RANK(数值, 区域, [升序])', '排名'],
    'RANK.EQ': ['RANK.EQ(数值, 区域, [升序])', '排名'],
    MEDIAN: ['MEDIAN(数值1, …)', '中位数'],
    STDEV: ['STDEV(数值1, …)', '样本标准差'],
    STDEVP: ['STDEVP(数值1, …)', '总体标准差'],
    VAR: ['VAR(数值1, …)', '样本方差'],
    LARGE: ['LARGE(区域, k)', '第 k 大的值'],
    SMALL: ['SMALL(区域, k)', '第 k 小的值'],
    LEN: ['LEN(文本)', '文本长度'],
    LEFT: ['LEFT(文本, [字符数])', '从左侧截取'],
    RIGHT: ['RIGHT(文本, [字符数])', '从右侧截取'],
    MID: ['MID(文本, 起始位置, 字符数)', '从中间截取'],
    UPPER: ['UPPER(文本)', '转为大写'], LOWER: ['LOWER(文本)', '转为小写'], PROPER: ['PROPER(文本)', '首字母大写'],
    TRIM: ['TRIM(文本)', '删除多余空格'],
    CONCAT: ['CONCAT(文本1, [文本2], …)', '连接文本（支持区域）'],
    CONCATENATE: ['CONCATENATE(文本1, [文本2], …)', '连接文本'],
    TEXTJOIN: ['TEXTJOIN(分隔符, 忽略空值, 文本1, …)', '用分隔符连接文本'],
    TEXT: ['TEXT(数值, 格式)', '按格式转换为文本'],
    VALUE: ['VALUE(文本)', '文本转数字'],
    FIND: ['FIND(查找文本, 文本, [起始位置])', '查找位置（区分大小写）'],
    SEARCH: ['SEARCH(查找文本, 文本, [起始位置])', '查找位置（不区分大小写，支持通配符）'],
    SUBSTITUTE: ['SUBSTITUTE(文本, 旧文本, 新文本, [第几个])', '替换文本'],
    REPLACE: ['REPLACE(文本, 起始位置, 字符数, 新文本)', '按位置替换'],
    REPT: ['REPT(文本, 次数)', '重复文本'],
    EXACT: ['EXACT(文本1, 文本2)', '是否完全相同'],
    VLOOKUP: ['VLOOKUP(查找值, 表格区域, 列序号, [近似匹配])', '按列查找'],
    HLOOKUP: ['HLOOKUP(查找值, 表格区域, 行序号, [近似匹配])', '按行查找'],
    XLOOKUP: ['XLOOKUP(查找值, 查找区域, 返回区域, [未找到], [匹配模式], [搜索模式])', '查找并返回'],
    LOOKUP: ['LOOKUP(查找值, 查找区域, [结果区域])', '查找'],
    INDEX: ['INDEX(区域, 行号, [列号])', '返回区域中指定位置的值'],
    MATCH: ['MATCH(查找值, 查找区域, [匹配类型])', '返回位置'],
    CHOOSE: ['CHOOSE(序号, 值1, 值2, …)', '按序号选择'],
    ROW: ['ROW([引用])', '行号'], COLUMN: ['COLUMN([引用])', '列号'], ROWS: ['ROWS(区域)', '行数'], COLUMNS: ['COLUMNS(区域)', '列数'],
    TODAY: ['TODAY()', '今天的日期'],
    NOW: ['NOW()', '当前日期和时间'],
    DATE: ['DATE(年, 月, 日)', '构造日期'],
    TIME: ['TIME(时, 分, 秒)', '构造时间'],
    YEAR: ['YEAR(日期)', '年份'], MONTH: ['MONTH(日期)', '月份'], DAY: ['DAY(日期)', '日'],
    HOUR: ['HOUR(时间)', '小时'], MINUTE: ['MINUTE(时间)', '分钟'], SECOND: ['SECOND(时间)', '秒'],
    WEEKDAY: ['WEEKDAY(日期, [类型])', '星期几'],
    EDATE: ['EDATE(开始日期, 月数)', '若干月之后的日期'],
    EOMONTH: ['EOMONTH(开始日期, 月数)', '月末日期'],
    DATEDIF: ['DATEDIF(开始日期, 结束日期, 单位)', '日期差（"Y" / "M" / "D"）'],
    DAYS: ['DAYS(结束日期, 开始日期)', '相差天数'],
    ISBLANK: ['ISBLANK(值)', '是否为空'], ISNUMBER: ['ISNUMBER(值)', '是否为数字'], ISTEXT: ['ISTEXT(值)', '是否为文本'],
    ISERROR: ['ISERROR(值)', '是否为错误值'], ISNA: ['ISNA(值)', '是否为 #N/A'],
}
