// 视频剪辑冒烟测试
const TMP = process.cwd().replace(/\\/g, '/') + '/.tmp'
const WIN = p => p.replace(/\//g, '\\')

export default async ({ theme, js, shot, wait, key, drag, click, log }) => {
    // 0. 新建空白项目（空状态界面）
    await js(`await window.app.openEditor('video', { name: '未命名视频', options: {} })`)
    await wait(700)
    await shot('empty')

    // 1. 在页面中用 mediabunny 生成 3 秒测试视频（画布动画 + 440Hz 音调）
    const src = WIN(TMP + '/video-src.mp4')
    const size = await js(`
        const MB = await window.app.active.editor.constructor.mediabunny()
        const W = 640, H = 360, fps = 30, dur = 3
        const canvas = new OffscreenCanvas(W, H), g = canvas.getContext('2d')
        const target = new MB.BufferTarget()
        const out = new MB.Output({ format: new MB.Mp4OutputFormat({ fastStart: 'in-memory' }), target })
        const vs = new MB.CanvasSource(canvas, { codec: 'avc', quality: MB.QUALITY_MEDIUM })
        const as = new MB.AudioBufferSource({ codec: 'aac', quality: MB.QUALITY_MEDIUM })
        out.addVideoTrack(vs, { frameRate: fps }); out.addAudioTrack(as)
        await out.start()
        for (let i = 0; i < fps * dur; i++) {
            const t = i / fps
            g.fillStyle = 'hsl(' + (t * 120) + ', 70%, 45%)'; g.fillRect(0, 0, W, H)
            g.fillStyle = '#fff'; g.beginPath(); g.arc(60 + t * 170, H / 2, 40, 0, 7); g.fill()
            g.font = 'bold 64px sans-serif'; g.fillText(t.toFixed(1), 440, 90)
            await vs.add(t, 1 / fps)
        }
        const sr = 48000, buf = new AudioBuffer({ length: sr * dur, numberOfChannels: 2, sampleRate: sr })
        for (let c = 0; c < 2; c++) { const d = buf.getChannelData(c); for (let i = 0; i < d.length; i++) d[i] = Math.sin(i / sr * 2 * Math.PI * 440) * 0.3 * (Math.floor(i / sr * 2) % 2 ? 1 : 0.3) }
        await as.add(buf)
        vs.close(); as.close()
        await out.finalize()
        const bytes = new Uint8Array(target.buffer)
        await window.lite.writeFile(${JSON.stringify(src)}, bytes)
        return bytes.length`)
    log('generated bytes', size)

    // 2. 打开 mp4
    await js(`await window.app.openPaths([${JSON.stringify(src)}])`)
    await wait(1500)
    const info = await js(`const e = window.app.active.editor; return { kind: e.kind, w: e.proj.width, h: e.proj.height, clips: e.proj.clips.length, dur: e.duration(), media: e.proj.media[0] }`)
    log('opened', JSON.stringify(info))
    if (info.kind !== 'video' || info.clips !== 1) throw new Error('打开视频失败')
    if (Math.abs(info.dur - 3) > 0.2) throw new Error('时长不正确 ' + info.dur)
    if (!info.media.hasAudio) throw new Error('未检测到音频')
    await wait(1200)
    await js(`const e = window.app.active.editor; e.seek(1.5)`)
    await wait(600)
    await shot('opened')
    // 预览画面非黑
    const px = await js(`const e = window.app.active.editor; const d = e.pvCtx.getImageData(e.pv.width / 2, 10, 1, 1).data; return Array.from(d)`)
    log('preview px', JSON.stringify(px))
    if (px[0] + px[1] + px[2] < 30) throw new Error('预览没有画面')
    const thumbs = await js(`const e = window.app.active.editor; const a = [...e.assets.values()][0]; return { thumbs: a.thumbs.length, peaks: !!a.peaks }`)
    log('analysis', JSON.stringify(thumbs))

    // 3. 分割 / 删除 / 撤销
    await js(`const e = window.app.active.editor; e.setSel([]); e.seek(1); e.splitAtPlayhead()`)
    let n = await js(`return window.app.active.editor.proj.clips.length`)
    if (n !== 2) throw new Error('分割失败')
    await js(`const e = window.app.active.editor; e.setSel([e.proj.clips[0].id]); e.deleteSel(true)`)
    const afterRipple = await js(`const e = window.app.active.editor; return { n: e.proj.clips.length, start: e.proj.clips[0].start, in: e.proj.clips[0].in, dur: e.duration() }`)
    log('ripple', JSON.stringify(afterRipple))
    if (afterRipple.n !== 1 || afterRipple.start !== 0 || Math.abs(afterRipple.in - 1) > 0.01) throw new Error('波纹删除失败')
    await js(`window.app.active.editor.undo()`)
    n = await js(`return window.app.active.editor.proj.clips.length`)
    if (n !== 2) throw new Error('撤销失败')
    await js(`window.app.active.editor.undo()`)
    n = await js(`return window.app.active.editor.proj.clips.length`)
    if (n !== 1) throw new Error('撤销分割失败')

    // 4. 鼠标修剪：拖动片段右边缘向左
    const edge = await js(`const e = window.app.active.editor; e.setSel([e.proj.clips[0].id]); e.drawTimeline(); const r = e.tl.getBoundingClientRect(); const c = e.proj.clips[0]; const row = e.trackRows().find(r => r.tr.id === c.track); return { x: r.left + e.tx(c.start + 3) - 2, y: r.top + row.y + row.h / 2, pps: e.pps }`)
    await drag(edge.x, edge.y, edge.x - edge.pps * 0.5, edge.y, 8)
    const trimmed = await js(`const c = window.app.active.editor.proj.clips[0]; return { out: c.out, in: c.in }`)
    log('trim', JSON.stringify(trimmed))
    if (!(trimmed.out < 2.8 && trimmed.out > 2.2)) throw new Error('修剪失败')
    // 鼠标移动：拖动片段向右
    const mid = await js(`const e = window.app.active.editor; const r = e.tl.getBoundingClientRect(); const c = e.proj.clips[0]; const row = e.trackRows().find(r => r.tr.id === c.track); return { x: r.left + e.tx(1), y: r.top + row.y + row.h / 2 + 8, pps: e.pps }`)
    await drag(mid.x, mid.y, mid.x + mid.pps * 0.6, mid.y, 8)
    const moved = await js(`return window.app.active.editor.proj.clips[0].start`)
    log('moved start', moved)
    if (!(moved > 0.3)) throw new Error('拖动移动失败')
    await js(`window.app.active.editor.undo()`)

    // 5. 字幕 + 转场
    await js(`const e = window.app.active.editor; e.seek(0.5); const t = e.addText('subtitle'); t.text = 'LiteEditor 视频剪辑'; e.change('文字'); e.proj.clips.find(c => c.type === 'video').fadeIn = 0.5; e.change('淡入'); e.seek(1.2)`)
    await wait(800)
    await shot('subtitle')
    const tracks = await js(`const e = window.app.active.editor; return e.proj.tracks.map(t => t.type + ':' + e.proj.clips.filter(c => c.track === t.id).length).join(',')`)
    log('tracks', tracks)

    // 6. 保存 .lvideo 并重新打开
    const proj = WIN(TMP + '/video-test.lvideo')
    await js(`await window.app.active.editor.writeTo(${JSON.stringify(proj)})`)
    const before = await js(`const e = window.app.active.editor; return JSON.stringify(e.proj.clips.map(c => [c.type, +c.start.toFixed(3), +c.in.toFixed(3), +c.out.toFixed(3)]))`)
    await js(`const t = window.app.active; window.app.closeTab(t)`)
    await wait(400)
    await js(`await window.app.openPaths([${JSON.stringify(proj)}])`)
    await wait(1200)
    const after = await js(`const e = window.app.active.editor; return JSON.stringify(e.proj.clips.map(c => [c.type, +c.start.toFixed(3), +c.in.toFixed(3), +c.out.toFixed(3)]))`)
    log('reload', after)
    if (before !== after) throw new Error('保存后重新打开不一致\n' + before + '\n' + after)

    // 7. 导出 MP4 并用 mediabunny 验证
    const outMp4 = WIN(TMP + '/video-export.mp4')
    const t0 = Date.now()
    await js(`const e = window.app.active.editor; const data = await e.runExport({ container: 'mp4' }); await window.lite.writeFile(${JSON.stringify(outMp4)}, data); return data.length`)
    log('export ms', Date.now() - t0)
    const check = await js(`
        const MB = await window.app.active.editor.constructor.mediabunny()
        const bytes = await window.lite.readFile(${JSON.stringify(outMp4)})
        const input = new MB.Input({ formats: MB.ALL_FORMATS, source: new MB.BufferSource(bytes) })
        const vt = await input.getPrimaryVideoTrack(), at = await input.getPrimaryAudioTrack()
        const dur = await input.computeDuration()
        const sink = new MB.CanvasSink(vt)
        const f = await sink.getCanvas(1.2)
        const px = Array.from(f.canvas.getContext('2d').getImageData(f.canvas.width / 2, 10, 1, 1).data)
        return { size: bytes.length, dur, w: await vt.getDisplayWidth(), h: await vt.getDisplayHeight(), vcodec: await vt.getCodec(), acodec: at && await at.getCodec(), px }`)
    log('mp4', JSON.stringify(check))
    const expDur = await js(`return window.app.active.editor.duration()`)
    if (Math.abs(check.dur - expDur) > 0.2) throw new Error('导出时长不正确')
    if (check.vcodec !== 'avc' || check.acodec !== 'aac') throw new Error('编码不正确')

    // 8. WAV / PNG / WebM
    const wav = await js(`const d = await window.app.active.editor.runAudioExport('wav'); return d.length`)
    log('wav bytes', wav)
    const png = await js(`const m = await import('/src/editors/video/export.js').catch(() => null); const e = window.app.active.editor; const f = e.exports().find(x => x.ext === 'png'); const d = await f.write(); return d.length`)
    log('png bytes', png)
    const webm = await js(`const e = window.app.active.editor; const d = await e.runExport({ container: 'webm', quality: 'low' }); return d.length`)
    log('webm bytes', webm)

    // 9. 截图：选中片段、浅色主题
    await js(`const e = window.app.active.editor; e.setSel([e.proj.clips.find(c => c.type === 'video').id]); e.seek(1.3)`)
    await wait(700)
    await shot('inspector')
    await js(`const e = window.app.active.editor; e.ptab = 'media'; e.refreshPanels()`)
    await wait(300)
    await shot('media')
    await theme('dark'); await js(`const e = window.app.active.editor; e.ptab = 'clip'; e.setSel([e.proj.clips.find(c => c.type === 'text').id])`)
    await wait(800)
    await js(`window.app.active.editor.renderAll()`)
    await wait(300)
    await shot('dark-text')
    await js(`const e = window.app.active.editor; e.ptab = 'project'; e.refreshPanels()`)
    await wait(300)
    await shot('dark-project')
    // 播放 1 秒
    await js(`window.app.active.editor.seek(0); window.app.active.editor.play()`)
    await wait(300)
    log('playing?', JSON.stringify(await js(`const e = window.app.active.editor; return { p: e.playing, t: e.time, d: e.duration(), hidden: e.el.hidden, modal: !!document.querySelector('.modal-mask') }`)))
    await wait(700)
    const playT = await js(`const e = window.app.active.editor; const t = e.time; e.pause(); return t`)
    log('played to', playT)
    if (!(playT > 0.3)) throw new Error('播放未前进')
}
